services:

  server:
    depends_on:
      - database
    image: tomcat:8.5.73-jdk8-corretto
    container_name: tomcat_exchange
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./../Server/target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./../Web/target/app.war:/usr/local/tomcat/webapps/app.war
    networks:
      - backend

  database:
    image: postgres
    container_name: database_exchange
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BarterExchangeDB
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./../Database/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:2021-08-09-1
    container_name: pgadmin_exchange
    restart: on-failure
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - backend

volumes:
  postgres:
  pgadmin:

networks:
  backend: